Repository pluxity/plug-platform, pull requests merged in 2025-07, with the labels that each got.

#129 feat(backoffice): designSystem sidebar 컴포넌트 및 backoffice sidebar/layo…
  apps/core/src/backoffice/common/services/.gitkeep
  apps/core/src/backoffice/common/services/layout.ts
  apps/core/src/backoffice/common/view/components/BackofficeHeader.tsx
  apps/core/src/backoffice/common/view/components/PageContainer.tsx
  apps/core/src/backoffice/common/view/layouts/BackofficeLayout.tsx
  apps/core/src/backoffice/pages/asset/index.tsx
  apps/core/src/backoffice/pages/device/index.tsx
  apps/core/src/global/router/AppRouter.tsx
  apps/core/vite.config.ts
  packages/ui/src/components/organism/Sidebar/Sidebar.stories.tsx
  packages/ui/src/components/organism/Sidebar/Sidebar.tsx
Labels: enhancement, project: admin

#133 Feature/backoffice asset
  apps/core/src/backoffice/common/view/layouts/BackofficeHeader.tsx
  apps/core/src/backoffice/common/view/layouts/BackofficeLayout.tsx
  apps/core/src/backoffice/domains/asset/components/assetCreateModal.tsx
  apps/core/src/backoffice/domains/asset/components/assetEditModal.tsx
  apps/core/src/backoffice/domains/asset/index.tsx
  apps/core/src/backoffice/domains/asset/mapper/assetMapper.tsx
  apps/core/src/backoffice/domains/asset/page/assetCategory.tsx
  apps/core/src/backoffice/domains/asset/page/assetList.tsx
  apps/core/src/backoffice/domains/asset/types/asset.ts
  apps/core/src/global/router/AppRouter.tsx
  packages/common-services/src/services/asset.ts
  packages/ui/src/components/atom/Dialog/Dialog.tsx
  packages/ui/src/components/organism/DataTable/DataTable.tsx
Labels: enhancement, project: admin

#135 feat(backoffice): role 페이지 생성
  apps/core/src/backoffice/common/view/layouts/BackofficeLayout.tsx
  apps/core/src/backoffice/domains/asset/components/assetCreateModal.tsx
  apps/core/src/backoffice/domains/asset/components/assetEditModal.tsx
  apps/core/src/backoffice/domains/asset/index.ts
  apps/core/src/backoffice/domains/asset/mapper/assetMapper.ts
  apps/core/src/backoffice/domains/asset/page/assetList.tsx
  apps/core/src/backoffice/domains/asset/types/asset.ts
  apps/core/src/backoffice/domains/users/components/roleCreateModal.tsx
  apps/core/src/backoffice/domains/users/components/roleEditModal.tsx
  apps/core/src/backoffice/domains/users/index.tsx
  apps/core/src/backoffice/domains/users/mapper/roleMapper.ts
  apps/core/src/backoffice/domains/users/page/Role.tsx
  apps/core/src/backoffice/domains/users/types/role.ts
  apps/core/src/global/router/AppRouter.tsx
  packages/common-services/src/services/asset.ts
  packages/common-services/src/services/role.ts
  packages/common-services/src/types/role.ts
Labels: enhancement, project: admin

#139 refactor: modalform controller 묶어서 추가 수정
  packages/ui/src/components/molecule/ModalForm/ModalForm.stories.tsx
  packages/ui/src/components/molecule/ModalForm/ModalForm.tsx
  packages/ui/src/components/molecule/ModalForm/ModalForm.types.ts
Labels: enhancement, project: design-system

#140 feature(organism) : LoginForm 작업 완료
  packages/ui/src/components/organism/LoginForm/LoginForm.stories.tsx
  packages/ui/src/components/organism/LoginForm/LoginForm.tsx
  packages/ui/src/components/organism/LoginForm/index.ts
  packages/ui/src/components/organism/index.ts
Labels: enhancement

#136 Feature/backoffice user
  apps/core/src/backoffice/common/view/components/category/CategoryComponent.tsx
  apps/core/src/backoffice/common/view/layouts/BackofficeLayout.tsx
  apps/core/src/backoffice/domains/asset/page/AssetList.tsx
  apps/core/src/backoffice/domains/users/components/UserCreateModal.tsx
  apps/core/src/backoffice/domains/users/components/UserEditModal.tsx
  apps/core/src/backoffice/domains/users/index.ts
  apps/core/src/backoffice/domains/users/mapper/userMapper.ts
  apps/core/src/backoffice/domains/users/page/User.tsx
  apps/core/src/backoffice/domains/users/types/user.ts
  apps/core/src/global/router/AppRouter.tsx
  packages/common-services/src/services/index.ts
  packages/common-services/src/services/user-admin.ts
  packages/common-services/src/services/user_admin.ts
  packages/common-services/src/types/user.ts
  pnpm-lock.yaml
Labels: enhancement, project: admin

#142 refactor: asset/role modalform 수정
  apps/core/src/backoffice/domains/asset/components/AssetCreateModal.tsx
  apps/core/src/backoffice/domains/asset/components/AssetEditModal.tsx
  apps/core/src/backoffice/domains/users/components/RoleCreateModal.tsx
  apps/core/src/backoffice/domains/users/components/RoleEditModal.tsx
Labels: enhancement, project: admin
