Repository pluxity/plug-platform, pull requests merged in 2025-06, with the labels that each got.

#108 [project/sasang/facility] 역사 관리 페이지 main 브랜치에 병합
  apps/v1/src/admin/pages/facility/component/FacilityModal.tsx
  apps/v1/src/admin/pages/facility/hook/useFacility.ts
  apps/v1/src/admin/pages/facility/hook/useStationDetail.ts
  apps/v1/src/admin/pages/facility/page/FacilitiesDetailPage.tsx
  packages/engine/src/model.ts
Labels: enhancement

#110 [project/sasang/feature/header] 전반적인 UI/UX 개선
  apps/v1/src/admin/pages/AdminLayout.tsx
  apps/v1/src/admin/pages/Asset/Management.tsx
  apps/v1/src/admin/pages/Asset/utils/useAsset.tsx
  apps/v1/src/admin/pages/Dashboard/Dashboard.tsx
  apps/v1/src/admin/pages/Dashboard/constants/DashboardTitle.ts
  apps/v1/src/admin/pages/Device/Category.tsx
  apps/v1/src/admin/pages/Device/Management.tsx
  apps/v1/src/admin/pages/Device/components/CategoryModal.tsx
  apps/v1/src/admin/pages/Device/utils/useCategory.tsx
  apps/v1/src/admin/pages/Device/utils/useDevice.tsx
  apps/v1/src/admin/pages/Line/Management.tsx
  apps/v1/src/admin/pages/Line/utils/useLine.tsx
  apps/v1/src/admin/pages/User/Management.tsx
  apps/v1/src/admin/pages/User/utils/useUser.tsx
  apps/v1/src/admin/pages/facility/component/FacilityModal.tsx
  apps/v1/src/admin/pages/facility/component/FileUploadField.tsx
  apps/v1/src/admin/pages/facility/page/FacilitiesDetailPage.tsx
  apps/v1/src/admin/pages/facility/page/FacilitiesPage.tsx
  apps/v1/src/app/api/clients/nflux.ts
  apps/v1/src/auth/api/auth.ts
  apps/v1/src/auth/controller/useProfileStore.ts
  apps/v1/src/auth/model/profile.ts
  apps/v1/src/auth/model/roles.ts
  apps/v1/src/auth/view/LoginPage.tsx
  apps/v1/src/router/ProtectedRoute.tsx
  apps/v1/src/router/admin/AdminRouter.tsx
  apps/v1/src/router/service/ServiceRouter.tsx
  packages/common-services/src/types/auth.ts
  packages/common-services/src/types/device_category.ts
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/Card/Card.tsx
  packages/ui/src/components/DataTable/DataTable.tsx
  packages/ui/src/components/Pagination/Pagination.tsx
  packages/ui/src/components/Sidebar/Sidebar.tsx
  packages/ui/src/index.css
Labels: enhancement

#113 [project/sasang/feature/toast] station commonservice로 이관, 토스트 & confirm 추가
  apps/v1/index.html
  apps/v1/src/admin/components/boundary/StateInfo.tsx
  apps/v1/src/admin/components/boundary/StateInfoWrapper.tsx
  apps/v1/src/admin/components/hook/useToastStore.tsx
  apps/v1/src/admin/components/modals/AssetRegist.tsx
  apps/v1/src/admin/components/modals/PoiBatRegist.tsx
  apps/v1/src/admin/components/toast/ToastContainer.tsx
  apps/v1/src/admin/pages/AdminLayout.tsx
  apps/v1/src/admin/pages/Asset/Management.tsx
  apps/v1/src/admin/pages/Asset/components/AssetModal.tsx
  apps/v1/src/admin/pages/Asset/constants/assetColumns.ts
  apps/v1/src/admin/pages/Asset/types/asset.types.ts
  apps/v1/src/admin/pages/Asset/utils/useAsset.tsx
  apps/v1/src/admin/pages/Dashboard/Dashboard.tsx
  apps/v1/src/admin/pages/Dashboard/constants/DashboardTitle.ts
  apps/v1/src/admin/pages/Device/Category.tsx
  apps/v1/src/admin/pages/Device/Management.tsx
  apps/v1/src/admin/pages/Device/components/CategoryModal.tsx
  apps/v1/src/admin/pages/Device/components/DeviceModal.tsx
  apps/v1/src/admin/pages/Device/constants/deviceColumns.ts
  apps/v1/src/admin/pages/Line/Management.tsx
  apps/v1/src/admin/pages/Line/components/LineModal.tsx
  apps/v1/src/admin/pages/User/Management.tsx
  apps/v1/src/admin/pages/User/components/UserModal.tsx
  apps/v1/src/admin/pages/User/components/UserPasswordModal.tsx
  apps/v1/src/admin/pages/User/components/UserRoleModal.tsx
  apps/v1/src/admin/pages/Viewer/ViewerPage.tsx
  apps/v1/src/admin/pages/Viewer/components/AssetList.tsx
  apps/v1/src/admin/pages/Viewer/components/PoiEditModal.tsx
  apps/v1/src/admin/pages/facility/api/station.ts
  apps/v1/src/admin/pages/facility/component/FacilityModal.tsx
  apps/v1/src/admin/pages/facility/component/FileUploadField.tsx
  apps/v1/src/admin/pages/facility/hook/useFacility.ts
  apps/v1/src/admin/pages/facility/hook/useFileUploader.ts
  apps/v1/src/admin/pages/facility/hook/useStationDetail.ts
  apps/v1/src/admin/pages/facility/page/FacilitiesDetailPage.tsx
  apps/v1/src/admin/pages/facility/page/FacilitiesPage.tsx
  apps/v1/src/admin/pages/facility/types/facility.ts
  apps/v1/src/admin/pages/facility/types/file.ts
  apps/v1/src/app/modules/view/pages/ViewerPage.tsx
  packages/common-services/src/services/asset.ts
  packages/common-services/src/services/device.ts
  packages/common-services/src/services/device_category.ts
  packages/common-services/src/services/file.ts
  packages/common-services/src/services/station.ts
  packages/common-services/src/types/asset.ts
  packages/common-services/src/types/device_category.ts
  packages/common-services/src/types/facility.ts
  packages/common-services/src/types/file.ts
  packages/common-services/src/types/station.ts
  packages/ui/src/components/Pagination/Pagination.tsx
  packages/ui/src/components/Toast/Toast.tsx
Labels: enhancement, project: sasang-hadan

#115 [project/sasang/feature/eventsource] eventsource 연결
  apps/v1/src/admin/pages/AdminLayout.tsx
  apps/v1/src/app/modules/components/map/MapViewer.tsx
  apps/v1/src/app/modules/view/layouts/Header/Header.tsx
  apps/v1/src/app/modules/view/layouts/Header/UserProfile.tsx
  apps/v1/src/app/modules/view/layouts/SideMenu/DevicePanel.tsx
  apps/v1/src/app/modules/view/layouts/SideMenu/MenuItem.tsx
  apps/v1/src/app/modules/view/layouts/SideMenu/SideMenu.tsx
  apps/v1/src/app/modules/view/pages/ViewerPage.tsx
  apps/v1/src/app/modules/view/types/stream.ts
  apps/v1/src/app/stores/eventSourceStore.ts
  apps/v1/src/app/stores/stationStore.ts
  apps/v1/vite.config.ts
Labels: project: sasang-hadan

#116 feature(admin) : 관리자 페이지 뷰어 작업 완료
  apps/v1/src/admin/components/hook/useToastStore.tsx
  apps/v1/src/admin/components/toast/ToastContainer.tsx
  apps/v1/src/admin/pages/Viewer/ViewerPage.tsx
  apps/v1/src/admin/pages/Viewer/components/FeatureEditToolbar.tsx
  apps/v1/src/admin/pages/Viewer/components/MapViewer.tsx
  apps/v1/src/admin/pages/Viewer/components/PoiEditModal.tsx
  apps/v1/src/admin/pages/Viewer/hooks/index.ts
  apps/v1/src/admin/pages/Viewer/hooks/useEditMode.ts
  apps/v1/src/admin/pages/Viewer/hooks/useEngineIntegration.ts
  apps/v1/src/admin/pages/Viewer/hooks/useFeatureApi.ts
  apps/v1/src/common/libs/engine/types.ts
  apps/v1/src/common/libs/engine/useEngineIntegration.ts
  packages/ui/src/components/ConfirmModal/ConfirmModal.tsx
  packages/ui/src/components/ConfirmModal/ConfirmModal.types.ts
  packages/ui/src/components/ConfirmModal/index.ts
  packages/ui/src/components/Form/Form.tsx
  packages/ui/src/components/Form/Form.types.ts
  packages/ui/src/components/Modal/Modal.tsx
  packages/ui/src/components/Select/Select.tsx
  packages/ui/src/components/Select/Select.types.ts
  packages/ui/src/components/Toast/Toast.types.ts
  packages/ui/src/components/Toast/index.ts
  packages/ui/src/index.components.ts
  packages/ui/src/index.type.ts
Labels: project: sasang-hadan

#118 hotfix(admin): 사용자 관리 수정 모달에서 아이디 입력 제거
  apps/v1/src/admin/pages/User/components/UserModal.tsx
  packages/common-services/src/types/user.ts
Labels: enhancement, project: sasang-hadan

#119 [project/sasang/bugs/station] 토스트 에러 응답 수정, data table 검색 수정
  apps/v1/src/admin/pages/Asset/Management.tsx
  apps/v1/src/admin/pages/Asset/components/AssetModal.tsx
  apps/v1/src/admin/pages/Device/Category.tsx
  apps/v1/src/admin/pages/Device/components/CategoryModal.tsx
  apps/v1/src/admin/pages/Device/components/DeviceModal.tsx
  apps/v1/src/admin/pages/Line/Management.tsx
  apps/v1/src/admin/pages/Line/components/LineModal.tsx
  apps/v1/src/admin/pages/User/Management.tsx
  apps/v1/src/admin/pages/User/components/UserModal.tsx
  apps/v1/src/admin/pages/User/components/UserPasswordModal.tsx
  apps/v1/src/admin/pages/User/components/UserRoleModal.tsx
  apps/v1/src/admin/pages/facility/hook/useFacility.ts
  apps/v1/src/admin/pages/facility/hook/useFileUploader.ts
  apps/v1/src/admin/pages/facility/hook/useStationDetail.ts
  apps/v1/src/admin/pages/facility/page/FacilitiesDetailPage.tsx
  apps/v1/src/admin/pages/facility/page/FacilitiesPage.tsx
  packages/common-services/src/services/user_admin.ts
  packages/ui/src/components/DataTable/DataTable.tsx
Labels: bug

#121 hofix(bug): data-table 전체 삭제 수정
  apps/v1/src/admin/pages/Asset/Management.tsx
  apps/v1/src/admin/pages/Device/Category.tsx
  apps/v1/src/admin/pages/Device/Management.tsx
  apps/v1/src/admin/pages/Device/components/DeviceModal.tsx
  apps/v1/src/admin/pages/Line/Management.tsx
  apps/v1/src/admin/pages/User/Management.tsx
  packages/ui/src/components/DataTable/DataTable.tsx
Labels: bug

#124 fix(design): service 페이지 디자인 수정
  apps/v1/index.html
  apps/v1/src/app/modules/view/layouts/EventCounter/EventCounter.tsx
  apps/v1/src/app/modules/view/layouts/Header/Header.tsx
  apps/v1/src/app/modules/view/layouts/Header/HeaderEnvInfo.tsx
  apps/v1/src/app/modules/view/layouts/Header/TimeDisplay.tsx
  apps/v1/src/app/modules/view/layouts/SideMenu/DevicePanel.tsx
  apps/v1/src/app/modules/view/layouts/SideMenu/MenuItem.tsx
  apps/v1/src/app/modules/view/layouts/SideMenu/SideMenu.tsx
Labels: enhancement, project: sasang-hadan

#125 fix: 삭제 시 confirm modal 동작 추가
  apps/v1/src/admin/pages/Asset/Management.tsx
  apps/v1/src/admin/pages/Asset/utils/useAsset.tsx
  apps/v1/src/admin/pages/Device/Category.tsx
  apps/v1/src/admin/pages/Device/Management.tsx
  apps/v1/src/admin/pages/Device/utils/useCategory.tsx
  apps/v1/src/admin/pages/Device/utils/useDevice.tsx
  apps/v1/src/admin/pages/Line/Management.tsx
  apps/v1/src/admin/pages/Line/utils/useLine.tsx
  apps/v1/src/admin/pages/User/Management.tsx
  apps/v1/src/admin/pages/User/utils/useUser.tsx
  apps/v1/src/admin/pages/facility/hook/useStationDetail.ts
  apps/v1/src/admin/pages/facility/page/FacilitiesDetailPage.tsx
  apps/v1/src/app/modules/components/modals/DeviceDetailModal.tsx
Labels: bug
