Repository pluxity/plug-platform, pull requests merged in 2025-04, with the labels that each got.

#71 toast 컴포넌트 생성
  packages/ui/src/components/Alert/Alert.stories.tsx
  packages/ui/src/components/Popup/Popup.stories.tsx
  packages/ui/src/components/Popup/Popup.tsx
  packages/ui/src/components/Popup/Popup.types.ts
  packages/ui/src/components/Toast/Toast.stories.tsx
  packages/ui/src/components/Toast/Toast.tsx
  packages/ui/src/components/Toast/Toast.types.ts
  packages/ui/src/components/Toast/index.ts
  packages/ui/src/components/types.ts
Labels: enhancement, project: design-system

#72 checkbox 컴포넌트 수정
  packages/ui/src/components/Checkbox/Checkbox.stories.tsx
  packages/ui/src/components/Checkbox/Checkbox.tsx
  packages/ui/src/components/Checkbox/Checkbox.types.ts
  packages/ui/src/components/Checkbox/index.ts
Labels: enhancement, project: design-system

#73 Design system/feature/toggle
  packages/ui/src/components/Toggle/Toggle.stories.tsx
  packages/ui/src/components/Toggle/Toggle.tsx
  packages/ui/src/components/Toggle/Toggle.types.ts
  packages/ui/src/components/Toggle/index.ts
  packages/ui/src/components/ToggleGroup/ToggleGroup.stories.tsx
  packages/ui/src/components/ToggleGroup/ToggleGroup.tsx
  packages/ui/src/components/ToggleGroup/ToggleGroup.types.ts
  packages/ui/src/components/ToggleGroup/index.ts
Labels: enhancement, project: design-system

#74 Design system/feature/carousel
  apps/sample/src/pages/DesignSystem.tsx
  packages/ui/package.json
  packages/ui/src/assets/icons/alert_error.svg
  packages/ui/src/assets/icons/alert_info.svg
  packages/ui/src/assets/icons/alert_notice.svg
  packages/ui/src/assets/icons/alert_success.svg
  packages/ui/src/components/Alert/.gitkeep
  packages/ui/src/components/Alert/Alert.stories.tsx
  packages/ui/src/components/Alert/Alert.tsx
  packages/ui/src/components/Alert/Alert.types.ts
  packages/ui/src/components/Alert/index.ts
  packages/ui/src/components/Badge/Badge.tsx
  packages/ui/src/components/Calendar/Calendar.stories.tsx
  packages/ui/src/components/Calendar/Calendar.tsx
  packages/ui/src/components/Calendar/Calendar.types.ts
  packages/ui/src/components/Carousel/Carousel.stories.tsx
  packages/ui/src/components/Carousel/Carousel.tsx
  packages/ui/src/components/Carousel/Carousel.types.ts
  packages/ui/src/components/Checkbox/Checkbox.stories.tsx
  packages/ui/src/components/Checkbox/Checkbox.tsx
  packages/ui/src/components/Checkbox/Checkbox.types.ts
  packages/ui/src/components/Checkbox/index.ts
  packages/ui/src/components/Popup/Popup.stories.tsx
  packages/ui/src/components/Popup/Popup.tsx
  packages/ui/src/components/Popup/Popup.types.ts
  packages/ui/src/components/Toast/Toast.stories.tsx
  packages/ui/src/components/Toast/Toast.tsx
  packages/ui/src/components/Toast/Toast.types.ts
  packages/ui/src/components/Toast/index.ts
  packages/ui/src/components/types.ts
  packages/ui/src/index.components.ts
  packages/ui/src/index.icons.ts
  packages/ui/src/index.ts
  packages/ui/src/index.type.ts
Labels: project: design-system

#75 Design system/feature/radio
  packages/ui/src/components/Radio/Radio.stories.tsx
  packages/ui/src/components/Radio/Radio.tsx
  packages/ui/src/components/Radio/Radio.types.ts
  packages/ui/src/components/Radio/index.ts
  packages/ui/src/components/Toast/index.ts
  packages/ui/src/components/ToggleGroup/ToggleGroup.tsx
Labels: enhancement, project: design-system

#78 feature(39-DataTable 컴포넌트)
  packages/ui/src/components/DataTable/DataTable.stories.tsx
  packages/ui/src/components/DataTable/DataTable.tsx
  packages/ui/src/components/DataTable/DataTable.types.ts
  packages/ui/src/components/DataTable/Pagination.tsx
  packages/ui/src/components/DataTable/SearchFilter.tsx
  packages/ui/src/components/DataTable/TableBody.tsx
  packages/ui/src/components/DataTable/TableHeader.tsx
  packages/ui/src/components/DataTable/index.ts
  packages/ui/src/index.components.ts
  packages/ui/src/index.type.ts
Labels: enhancement, project: design-system

#77 dropdown 컴포넌트 생성
  packages/ui/src/components/Dropdown/Dropdown.stories.tsx
  packages/ui/src/components/Dropdown/Dropdown.tsx
  packages/ui/src/components/Dropdown/Dropdown.types.ts
  packages/ui/src/components/Dropdown/index.ts
  packages/ui/src/components/Input/Input.tsx
Labels: enhancement, project: design-system

#80 feature(43-Paginatio 컴포넌트)
  packages/ui/src/components/DataTable/DataTable.tsx
  packages/ui/src/components/Pagination/Pagination.stories.tsx
  packages/ui/src/components/Pagination/Pagination.tsx
  packages/ui/src/components/Pagination/Pagination.types.ts
  packages/ui/src/components/Pagination/index.ts
Labels: enhancement, project: design-system

#81 UI/feature/combobox
  packages/ui/src/components/ComboBox/ComboBox.stories.tsx
  packages/ui/src/components/ComboBox/ComboBox.tsx
  packages/ui/src/components/ComboBox/ComboBox.types.ts
  packages/ui/src/components/ComboBox/index.ts
  packages/ui/src/index.components.ts
  packages/ui/src/index.type.ts
Labels: enhancement, project: design-system

#79 select 컴포넌트 생성
  packages/ui/src/assets/icons/select_close.svg
  packages/ui/src/components/Select/Select.stories.tsx
  packages/ui/src/components/Select/Select.tsx
  packages/ui/src/components/Select/Select.types.ts
  packages/ui/src/components/Select/index.ts
  packages/ui/src/index.components.ts
  packages/ui/src/index.icons.ts
  packages/ui/src/index.type.ts
Labels: enhancement, project: design-system

#82 sidebar 컴포넌트 생성
  apps/sample/src/pages/DesignSystem.tsx
  packages/ui/src/assets/icons/sidebar_arrow.svg
  packages/ui/src/components/Input/Input.tsx
  packages/ui/src/components/Sidebar/Sidebar.stories.tsx
  packages/ui/src/components/Sidebar/Sidebar.tsx
  packages/ui/src/components/Sidebar/Sidebar.types.ts
  packages/ui/src/components/Sidebar/index.ts
  packages/ui/src/components/ToggleGroup/ToggleGroup.tsx
  packages/ui/src/index.components.ts
  packages/ui/src/index.icons.ts
  pnpm-lock.yaml
Labels: enhancement, project: design-system

#86 sheet 컴포넌트 생성
  packages/ui/src/components/Popup/Popup.types.ts
  packages/ui/src/components/Sheet/Sheet.stories.tsx
  packages/ui/src/components/Sheet/Sheet.tsx
  packages/ui/src/components/Sheet/Sheet.types.ts
  packages/ui/src/components/Sheet/index.ts
  packages/ui/src/components/Toast/Toast.tsx
  packages/ui/src/components/Toast/Toast.types.ts
  packages/ui/src/components/Toast/index.ts
  packages/ui/src/components/Tooltip/Tooltip.types.ts
  packages/ui/src/components/types.ts
Labels: enhancement, project: design-system

#85 feature(41-Form 컴포넌트)
  package.json
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/Checkbox/Checkbox.tsx
  packages/ui/src/components/Checkbox/Checkbox.types.ts
  packages/ui/src/components/Dropdown/Dropdown.stories.tsx
  packages/ui/src/components/Form/Form.stories.tsx
  packages/ui/src/components/Form/Form.tsx
  packages/ui/src/components/Form/Form.types.ts
  packages/ui/src/components/Form/index.ts
  packages/ui/src/components/Form/useForm.ts
  packages/ui/src/components/Form/validationUtils.ts
  packages/ui/src/components/Input/Input.stories.tsx
  packages/ui/src/components/Input/Input.tsx
  packages/ui/src/components/Input/Input.types.ts
  packages/ui/src/components/Input/InputText.tsx
  packages/ui/src/components/Label/Label.stories.tsx
  packages/ui/src/components/Radio/Radio.tsx
  packages/ui/src/components/Radio/Radio.types.ts
Labels: project: design-system

#89 Hotfix(v1-project setting) 보일러프로젝트 작업(라우팅, 린트)
  .husky/pre-commit
  apps/v1/.eslintrc.cjs
  apps/v1/.gitignore
  apps/v1/.prettierignore
  apps/v1/.prettierrc
  apps/v1/README.md
  apps/v1/eslint.config.js
  apps/v1/index.html
  apps/v1/package.json
  apps/v1/public/.gitkeep
  apps/v1/src/App.tsx
  apps/v1/src/admin/pages/DashboardPage.tsx
  apps/v1/src/admin/pages/User.tsx
  apps/v1/src/main.tsx
  apps/v1/src/router/admin/AdminRouter.tsx
  apps/v1/src/router/admin/adminRoutes.ts
  apps/v1/src/router/index.tsx
  apps/v1/src/router/service/ServiceRouter.tsx
  apps/v1/src/router/service/serviceRoutes.ts
  apps/v1/src/service/pages/Home.tsx
  apps/v1/src/vite-env.d.ts
  apps/v1/tsconfig.app.json
  apps/v1/tsconfig.node.json
  apps/v1/vite.config.ts
  package.json
  packages/ui/src/index.icons.ts
  pnpm-lock.yaml
  tsconfig.json
Labels: enhancement
